### ISSUE TITLE
Windows 8.1 prof (64 bit), not able to run Boot2Docker

### ISSUE THREAD

**Issue by ajit555** [boot2docker/windows-installer#31]
Downloaded Windows installer from below:
https://github.com/boot2docker/windows-installer/releases/tag/v1.1.1

Uninstalled git and GitHub for windows from my system. Oracle Virtualbox is alreay installed in my system, I did not uninstall it.

Completely installed boot2docker and restarted the system.

On desktop, when click "Boot2Docker Start" link, it opens in my NotePad++. The file is:
C:\Program Files\Boot2Docker for Windows\start.sh

on Command prompt, if start command is given, the following message is displayed:
C:\Users\Ajit>boot2docker start
2014/07/18 16:33:43 Failed to get machine "boot2docker-vm": machine does not exist

**Comment by jampy** [comment]
I've had the exact same problem described here (.sh file association missing, `clear` not found). 

However, instead of polluting the PATH globally (even MSYS discourages to do that) I wrote a very simple .bat script that I use to start Boot2Docker:

```
set PATH=%PATH%;C:\Program Files (x86)\Git\bin
bash start.sh
```

This is placed in the Boot2Docker base directory (`C:\Program Files\Boot2Docker for Windows\start.bat`).

This solves two problems:
- the PATH environment is changed temporally, not globally
- no need for the .sh file association 

Now double-clicking on start**.bat** works like a charm.

**Comment by vdtidake** [comment]
Added the Git PATH to the environment variables and it worked :+1:

**Comment by dee-g** [comment]
adding this  C:\Program Files (x86)\Git\bin to PATH environment variable worked for me .

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
