### ISSUE TITLE
Using "Portable" versions of our deps could help smooth out environmental differences that break things

### ISSUE THREAD

**Issue by andreysaksonov** [boot2docker/windows-installer#43]
In case of Cygwin environment paths will be different.

I will provide patch to start.sh and delete.sh to determine the correct environment

**Comment by jampy** [comment]
See https://github.com/boot2docker/windows-installer/issues/31#issuecomment-76589931

Couldn't you just install (copy, without any installer) the msys directory as a sub-folder to the Boot2Docker installation (`C:\Program Files\Boot2Docker for Windows\msys`) and then, instead of having the user click on start**.sh**, use a **.bat** file that sets up the environment before calling the .sh script?

```
set PATH=%PATH%;%CD%\msys\bin
bash ./start.sh
```

...assuming that `bash` and all other msys UNIX tools can be found in `<boot2docker-dir>\msys\bin`

**Comment by jampy** [comment]
Note that my solution only helps to run the boot2docker shell itself, but the `boot2docker` command won't work in other terminals.

For example, `boot2docker ip` won't work because apparently it relies on Unix commands:

```
C:\Users\Udo>boot2docker ip

Failed to get VM Host only IP address.
        Was the VM initialized using boot2docker?
```
This is because the `PATH` is missing the directory to the Msys utils.

Perhaps, in a "msys portable" situation, the `boot2docker` command could set up the `PATH` by itself.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
