### ISSUE TITLE
boot2docker not found

### ISSUE THREAD

**Issue by bwfilms** [boot2docker/windows-installer#58]
I followed the instruction from this link https://docs.docker.com/installation/windows/. I ran the "Boot2Docker Start" script and I was able to "docker run hello-world" correctly.

However, "./boot2docker" is not available (I'm in the "/home/docker" directory). In this directory, I have a "boot2docker, please format-me" file/dir (the attributes contain only dashes "----------"). I also cannot continue with the "docker run --rm -i -t -p 80:80 nginx" (the command seems to be caught in a loop, but I'm able to Ctrl-C and return to the prompt). I also cannot do "boot2docker ip" as all I get is "-sh: boot2docker: not found"

Docker itself seems to work fine as I'm able to do all of the steps in https://docs.docker.com/userguide/dockerizing/.

Any help/hint you can provide is appreciated. Thanks...

**Comment by lucernae** [comment]
Maybe this is helpful. For those who also follow the User Guide for windows, I also look at the start.sh script on the Docker installation folder, and it actually includes command ./bootdocker.exe ip.
So the IP is actually printed out in the shell. At least this helps me a bit in that situation.

**Comment by shailesha** [comment]
Hi,
I am having the same problem. Docker is running fine in one of the virtual machines on virtualBox which was installed with docker toolbox. However, I am not able to run boot2docker command on any of the consoles. I dont see any .boot2docker directory in /home ( windows equivalent). I also searched for boot2docker.exe on my windows host but could not find.  I tried running this command from windows command prompt, MINGW64 bash console as well as from the linux terminal inside the virtual machine running boot2docker host but none of them are able to recognize this command.

what could be wrong. The docker is running fine otherwise. I am able to run docker examples.

**Comment by shailesha** [comment]
Just to add, I also looked at start.sh in the docker toolbox and it does not have any mention of boot2docker.exe. It only has boot2docker.iso file. Nor there is any link/shortcut for boot2docker.exe.
I want to run the command boot2docker ip

**Comment by shailesha** [comment]
docker-machine has the similar subcommands. It was my ignorance on docker.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
