### ISSUE TITLE
error in run: Failed to start machine "boot2docker-vm": Failed to start%!(EXTRA string=boot2docker-vm)

### ISSUE THREAD

**Issue by bluekeys** [boot2docker/windows-installer#63]
I'm getting the error from a fresh install of docker on win7 64. I have an existing installation of VirtualBox 4.2.0 r80737 and git.

**Comment by mwhooker** [comment]
I was running in to this error. Eventually it turned out that /Applications was owned by the incorrect user somehow. Try making sure it's owned by root. see https://forums.virtualbox.org/viewtopic.php?f=7&t=39179

**Comment by ssmith15** [comment]
I'm running into this issue too now on Windows Server 2012. can't restart, up, or start the machine. Virtual Box seems to be the issue. When I try to manually start the VM it doesn't work. Changing things like sh-->bash association didn't work for me. I can't paste from terminal right now but here's the gist:

VBoxManage.exe: error Shared folder c/users already exists
... create share folder (bstr(name).raw, btstr(hostpath).raw(), fWritable, fAutoMount) at like 1015 of file VBoxManageMisc.cpp
...
startvm boot2docker-vm type --headless
Waiting for vm to power on...
VM boot2docker-vm has been sucessfully started
error in run: Failed to start machine boot2docker-vm exit status 1

And the main issue is when i run boot2docker I don't even get to the ...ooo, it just hangs for a second and then crashes/the windows closes.

**Comment by Mletter1** [comment]
I appear to be running into something similar, not sure if its the same issue. here -v output 


$ boot2docker -v up
Boot2Docker-cli version: v1.7.1
Git commit: 8fdc6f5
2015/07/31 21:42:31 executing: F:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 showvminfo boot2docker-vm --machinereadable
2015/07/31 21:42:31 executing: F:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountPrefix
 /
2015/07/31 21:42:31 executing: F:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountDir /
2015/07/31 21:42:32 executing: F:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 sharedfolder add boot2docker-vm --name c/Users --hostpath C:\Users --automount
VBoxManage.exe: error: Shared folder named 'c/Users' already exists
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), componen
t SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostp
ath).raw(), fWritable, fAutoMount)" at line 1015 of file VBoxManageMisc.cpp
2015/07/31 21:42:32 executing: F:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 setextradata boot2docker-vm VBoxInternal2/SharedFoldersEnableSymlinksCreate/c/U
sers 1
2015/07/31 21:42:32 executing: F:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 startvm boot2docker-vm --type headless
Waiting for VM "boot2docker-vm" to power on...
VM "boot2docker-vm" has been successfully started.
error in run: Failed to start machine "boot2docker-vm": exit status 1

$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): windows/amd64
Get http://127.0.0.1:2375/v1.19/version: dial tcp 127.0.0.1:2375: ConnectEx tcp:
 No connection could be made because the target machine actively refused it.. Ar
e you trying to connect to a TLS-enabled daemon without TLS?

$ boot2docker ssh
error in run: VM "boot2docker-vm" is not running. (Did you run `boot2docker up`?
)

**Comment by Mletter1** [comment]
So I figured the the issue here, I had to go into my bios and turn on virtualization. Easy test for this is to simply start the boot2docker image in virtual box and see if you get a 
"VT-x is disabled in the BIOS. (VERR_VMX_MSR_VMXON_DISABLED)" error

http://stackoverflow.com/questions/20647610/verr-vmx-msr-vmxon-disabled-when-starting-an-image-from-oracle-virtual-box

**Comment by ssmith15** [comment]
what about virtual servers or access servers where you can't access the BIOS? If I'm trying to deploy to a virtual server wouldn't this be an issue?

**Comment by jackchendong** [comment]
I have the same problem
virtual servers is enable

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
