### ISSUE TITLE
Allow installation on 32bit Machines!

### ISSUE THREAD

**Issue by frank-dspeed** [boot2docker/windows-installer#65]
the iss script and software versions should be the 32bit versions because they are able to run 64bit vms still if the cpu supports that.

**Comment by StefanScherer** [comment]
I did a little test to build a 32bit boot2docker.iso. And yes, it is running, even in an AppVeyor CI server that has no nested hypervisor. 
If there is interest, I can send the PR to this repo. At the moment it is here: https://github.com/StefanScherer/boot2docker/pull/1

**Comment by StanAngeloff** [comment]
What is the current situation with running boot2docker on a 32-bit Windows host? I have a Lenovo Miix 3 with an Intel Atom processor with VT-x enabled. Virtualbox can run 64-bit Ubuntu and Alpine Linux (both from 64-bit ISOs). However I am unable to run boot2docker as it halts with:

![capture](https://cloud.githubusercontent.com/assets/93127/12867872/e6f0d5ec-cd01-11e5-99c1-8af48a242981.PNG)

I installed boot2docker from docker-machine 0.6.0.

Am I missing something? I'd be happy to open a new issue or provide more detailed information.

**EDIT**: CPU details:

![capture](https://cloud.githubusercontent.com/assets/93127/12867887/552dfbb6-cd02-11e5-9cfe-b79cb6820c9b.PNG)

alpine-3.3.1-x86_64.iso in Virtualbox:

![capture](https://cloud.githubusercontent.com/assets/93127/12867899/b26a25c0-cd02-11e5-94eb-097a710b4c53.PNG)

**Comment by StefanScherer** [comment]
@StanAngeloff Interesting.Probably different kernel configs. Could you run `zcat /proc/config.gz` in the Ubuntu/Alpine VMs?

**Comment by StanAngeloff** [comment]
@StefanScherer Thanks for your input! `/proc/config.gz` does not exist on Alpine, the closest I could get is [`/media/cdrom/boot/config-grsec`](https://gist.github.com/StanAngeloff/54b9a96edf934de760ea) (I'm live booting from an .iso).

**Comment by poshest** [comment]
+1 for supporting 32-bit Windows host when CPU supports virtualization. Otherwise I have to buy a 64 bit licence, reinstall Windows, reinstall and reconfigure my entire Win environment, just to use Docker.

**Comment by StefanScherer** [comment]
I have downloaded the boot2docker.iso from release 1.10 and did some tests on my 32bit Windows 10 PC with VirtualBox 5.0.14. I have a Core2Duo Q6600 CPU inside which has `wmic cpu get VirtualizationFirmwareEnabled` = TRUE 
So booting this ISO should work. And indeed creating a VirutalBox configuration with that ISO boots and docker is up and running with x86_64 kernel and binaries on my 32bit Windows host.

But creating a docker-machine does not work. This stops with the known error.

I have compared the `*.vbox` configuration files and found some differences that cause the problem in that situation win32 host -> x64 linux vm.

The working version of the `.vbox` configuration has
- PAE enabled="false"
- LongMode enabled="true"
- HardwareVirtExLargePages enabled="false"
- HPET enabled=false"

``` xml
    <Hardware version="2">
      <CPU count="1" hotplug="false">
        <HardwareVirtEx enabled="true"/>
        <HardwareVirtExNestedPaging enabled="true"/>
        <HardwareVirtExVPID enabled="true"/>
        <HardwareVirtExUX enabled="true"/>
        <PAE enabled="false"/>
        <LongMode enabled="true"/>
        <HardwareVirtExLargePages enabled="false"/>
        <HardwareVirtForce enabled="false"/>
      </CPU>
      <Memory RAMSize="1024" PageFusion="false"/>
      <HID Pointing="USBTablet" Keyboard="PS2Keyboard"/>
      <HPET enabled="false"/>
      <Chipset type="PIIX3"/>
      <Paravirt provider="Default"/>
```

I haven't looked closer if there are less than the four changes needed ot make it work.

So the problem is not the `boot2docker.iso` but the configuration of the VirtualBox VM. Perhaps the `docker-machine.exe` could create a win32-host-compatible version of the `*.vbox` file to make it work.

**Comment by StefanScherer** [comment]
Found it. Only changing the `<LongMode enabled="true"/>` did it.
See also VirtualBox issue [#12458 Vbox 4.3.4 not starting 64 bit guests](https://www.virtualbox.org/ticket/12458?cversion=0&cnum_hist=10).

**Comment by StefanScherer** [comment]
Opened PR docker/machine#3017 as a next step.

**Comment by StanAngeloff** [comment]
Excellent @StefanScherer, thank you!

**Comment by StanAngeloff** [comment]
I can confirm that after modifying the VM to enable long mode, boot2docker and docker-machine work as expected. I was unable to pull an image from the registry, but that is unrelated.

**Comment by haiqu** [comment]
BootToDocker 1.8.0 refuses to install on a 32-bit machine and all later versions also require 64-bit Windows. So am I right in assuming this was never completed?

**Comment by yosifkit** [comment]
@haiqu, this installer has been deprecated in favor of docker-toolbox: https://github.com/boot2docker/windows-installer#deprecated.  In order to get the fix that was applied in docker-machine, you need to have at least version docker version 1.11. That is the first release of docker-toolbox that contains a version of docker-machine that had the fix from docker/machine#3017. 
- https://github.com/docker/toolbox/releases/tag/v1.11.0
- https://github.com/docker/machine/releases/tag/v0.7.0
- https://github.com/docker/machine/commit/c40f9f7a215dd2cbc1bc31b0ace861a0e22b82f4

**Comment by haiqu** [comment]
Thanks for the comprehensive links. I did manage to find a binary of v1.11.0 and installed it a few days ago, but in the case of the project I was working on when I made this request , a native build was possible (with great difficulty) so I'll try it next time anyone calls for Docker. There are at least two more projects I've forked that "require" it.

Might be good to add a note and a link on your download pages since it isn't immediately obvious that Win64 is almost mandatory.
- Rob

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
