### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by dashingly** [boot2docker/windows-installer#76]
I used the Windows installer to install boot2docker.
However the resulting shortcut "Boot2Docker Start" both on desktop and in Start menu points to "C:\Program Files\Boot2Docker for Windows\start.sh".
This makes no sense since I it is windows, not Linux.

**Comment by SvenDowideit** [comment]
It does make sense. The windows installer installs MSYS-git, which contains `bash` and the other tools that the `docker` client relies on.

**Comment by dashingly** [comment]
Ok, I see your point. 
But the thing is - the shortcut does not call bash.

**Comment by SvenDowideit** [comment]
'normally' is does - I think if you already have `.sh` linked to something else (like an editor) then the MSYS installer doesn't seem to over-ride the choice.

I just tested on my windows box, and it worked.


can you provide more info about your system?

**Comment by hatzopoulos** [comment]
I have the same problem and it must have to do with my custom setup. In my case I have installed [msysGit](https://github.com/msysgit/msysgit) manually in order to compile my own version of Git. So when installing boot2docker I opted to not install it again. I don't have .sh files setup to run bash/sh and even trying to map the extension to run sh or bash fails bad in windows 7. It just doesn't keep the window open and closes it immediately. 

The only way I can run boot2docker is to
1. run `c:\path\to\msysgit\msys.bat` to open MingW32 cmd prompt
2. cd `/c/path/to/Boot2Docker`
3. `/start.sh`

I could likely speed this up by making my own batch file.

*p.s. fwiw I would not want my windows system to auto run .sh or .bash files anyways. From both a security standpoint and personal taste in that I want my bash/sh to open by default in my text editor.*

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
