### ISSUE TITLE
Had to comment out clear on start.sh

### ISSUE THREAD

**Issue by jcricaro** [boot2docker/windows-installer#97]
I had to comment out

line 5

```
clear
```

for it to work. I'm using **windows 8.1**

**Comment by SvenDowideit** [comment]
I'm also on windows 8.1, and its ok on mine.

I wonder if we have different versions of msysgit :/

**Comment by ianchanning** [comment]
I have three programs installed that all contain bash: [Gow][1], msysgit and [OpenSSH][2]. `clear` only works for msysgit. There are ways to [get the clear command to work in Gow bash][3], but I think that it would be simplest to remove the `clear` command as otherwise the script will run.

[1]: https://github.com/bmatzelle/gow
[2]: http://www.mls-software.com/opensshd.html
[3]: https://github.com/bmatzelle/gow/issues/55#issuecomment-99401287

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
